/* Nightfall Cape discover: filterable local event index with transparent prototype data. */
import { useMemo, useState } from "react";
import { Link } from "wouter";
import { ArrowLeft, ArrowUpRight, Search } from "lucide-react";
const events=[
 {title:"Neon Market",category:"Market",neighbourhood:"Salt River",time:"Tonight · 18:00",price:"R120",desc:"Records, handmade things, small plates, and one very good sound system."},
 {title:"Soft launch sessions",category:"Live music",neighbourhood:"Observatory",time:"Tonight · 20:00",price:"R120",desc:"A basement session for warm horns, low lights, and new arrangements."},
 {title:"Things in the dark",category:"After-dark art",neighbourhood:"CBD",time:"Tomorrow · 17:00",price:"Free",desc:"A small gallery walk through work that refuses to sit quietly."},
 {title:"Table for two",category:"Late plates",neighbourhood:"Woodstock",time:"Tonight · 19:30",price:"R–R250",desc:"An open kitchen, seasonal plates, and a table worth lingering at."},
 {title:"Harbour radio",category:"Live music",neighbourhood:"Sea Point",time:"Fri · 21:00",price:"R80",desc:"A listening room by the water with selectors from the peninsula."},
 {title:"Clay after hours",category:"Workshop",neighbourhood:"Salt River",time:"Sat · 16:00",price:"R240",desc:"Hands in the clay, music on the stereo, nothing to take too seriously."},
 {title:"Night swim cinema",category:"Film",neighbourhood:"Sea Point",time:"Sat · 19:00",price:"R160",desc:"A rooftop screening with a sea breeze and a short film programme."},
 {title:"Open studio / 06",category:"After-dark art",neighbourhood:"Woodstock",time:"Sun · 15:00",price:"Free",desc:"Studios open their doors for a slow afternoon of unfinished ideas."}
];
export default function Discover(){const [query,setQuery]=useState("");const [active,setActive]=useState("All");const cats=["All","Live music","Late plates","After-dark art","Market","Workshop","Film"];const filtered=useMemo(()=>events.filter(e=>(active==="All"||e.category===active)&&`${e.title} ${e.neighbourhood} ${e.desc}`.toLowerCase().includes(query.toLowerCase())),[query,active]);return <div><header className="nav scrolled"><Link href="/" className="brand"><span className="brand-mark"/>nightfall cape</Link><Link href="/" className="nav-note"><ArrowLeft size={14}/> back home</Link></header><main><section className="page-top"><div className="eyebrow">The index / 08 places to begin</div><h1>Make a<br/><em>plan.</em></h1><p className="hero-sub">Browse the city by mood, neighbourhood, or the thing you want to feel tonight.</p><div className="filterbar"><div style={{position:"relative",flex:"1 1 240px"}}><Search size={15} style={{position:"absolute",left:12,top:12,color:"#c4ff3d"}}/><input aria-label="Search events" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search the index" style={{width:"100%",padding:"10px 14px 10px 36px",background:"#11131b",border:"1px solid #282a35",color:"#f5f3ed",fontFamily:"DM Mono"}}/></div>{cats.map(c=><button key={c} className={`filter ${active===c?"active":""}`} onClick={()=>setActive(c)}>{c}</button>)}</div></section><section className="section" style={{paddingTop:65}}><div className="section-head"><div><div className="eyebrow">{filtered.length.toString().padStart(2,"0")} / Results</div><h2 className="section-title">The night,<br/><em>sorted.</em></h2></div><p className="section-copy">Fictional event data for a self-initiated prototype. Save the useful bits; the rest can wait.</p></div><div className="discover-grid">{filtered.map((e,i)=><Link className="discover-card" href="/case-study" key={e.title}><div className="event-meta"><span className="pill">{String(i+1).padStart(2,"0")}</span><span className="mono">{e.category}</span></div><h3>{e.title}</h3><p>{e.neighbourhood} · {e.time}<br/>{e.price}</p><p>{e.desc}</p><span className="arrow">↗</span></Link>)}</div>{filtered.length===0&&<div className="empty">Nothing matches that search. Try a neighbourhood, mood, or “music”.</div>}</section></main><footer className="footer"><div><strong>nightfall cape</strong><p className="disclosure">Fictional client · self-initiated brief · prototype</p></div><Link className="btn" href="/case-study">How this was made <ArrowUpRight size={15}/></Link></footer></div>}
