/* Nightfall Cape home: cinematic editorial landing page with useful discovery paths. */
import { useEffect, useState } from "react";
import { Link } from "wouter";
import { ArrowUpRight, Menu, X } from "lucide-react";

function Header() {
  const [scrolled, setScrolled] = useState(false);
  const [open, setOpen] = useState(false);
  useEffect(() => { const fn=()=>setScrolled(window.scrollY>24); window.addEventListener("scroll",fn); return()=>window.removeEventListener("scroll",fn); }, []);
  return <header className={`nav ${scrolled?"scrolled":""}`}><Link href="/" className="brand"><span className="brand-mark"/>nightfall cape</Link><nav className={open?"nav-links mobile-open":"nav-links"}><Link href="/discover">Discover</Link><Link href="/case-study">Case study</Link><a href="#places">Neighbourhoods</a></nav><span className="nav-note">Cape Town · 2026</span><button className="mobile-menu" aria-label="Toggle menu" onClick={()=>setOpen(!open)}>{open?<X size={20}/>:<Menu size={20}/>}</button></header>;
}
export default function Home(){return <div><Header/><main><section className="hero"><div className="hero-art"/><div className="hero-grid"/><div className="hero-content"><div className="eyebrow">Independent city guide / prototype</div><h1>Find your <em>night.</em></h1><p className="hero-sub">A visual guide to music, food, art, and small moments after sunset in Cape Town.</p><div className="actions"><Link className="btn primary" href="/discover">Explore tonight <ArrowUpRight size={15}/></Link><Link className="btn" href="/case-study">Read the case study</Link></div></div></section><div className="ticker"><div className="ticker-inner">{["music","food","late walks","local places","after-dark art","small rooms","music","food","late walks","local places","after-dark art","small rooms"].map((x,i)=><span key={i}><b>✳</b> {x}</span>)}</div></div><section className="section"><div className="section-head"><div><div className="eyebrow">01 / Featured tonight</div><h2 className="section-title">A little closer<br/>to the <em>good stuff.</em></h2></div><p className="section-copy">The places worth crossing town for. Curated with a little curiosity and no rush.</p></div><div className="events-grid"><Link className="event-card large" href="/discover"><div className="event-image"/><div className="event-content"><div className="event-meta"><span className="pill">Tonight · 18:00</span><span className="pill">Salt River</span></div><h3 className="event-title">Neon<br/>Market</h3><p className="event-desc">A night market of records, handmade things, small plates, and one very good sound system.</p></div></Link><div className="mini-stack"><div className="mini-event"><div><span className="mono">Live music / Observatory</span><h3>Soft launch sessions</h3><p>Basement jazz, 20:00 · R120</p></div><span className="arrow">↗</span></div><div className="mini-event"><div><span className="mono">Late plates / Woodstock</span><h3>Table for two</h3><p>Open kitchen, 19:30 · R–R250</p></div><span className="arrow">↗</span></div><div className="mini-event"><div><span className="mono">After-dark art / CBD</span><h3>Things in the dark</h3><p>Small gallery walk, 17:00 · Free</p></div><span className="arrow">↗</span></div></div></div></section><section id="places" className="places"><div className="eyebrow">02 / Choose a direction</div><h2 className="section-title">Where are you<br/><em>headed?</em></h2><p className="section-copy">Five corners of the city. Plenty of reasons to take the long way there.</p><div className="place-row">{["Observatory","Woodstock","CBD","Sea Point","Salt River"].map((p,i)=><Link href={`/discover?neighbourhood=${encodeURIComponent(p)}`} className="place" key={p}>{String(i+1).padStart(2,"0")} / {p}</Link>)}</div></section></main><footer className="footer"><div><strong>nightfall cape</strong><p className="disclosure">Fictional client · self-initiated brief · prototype</p></div><div><p>Make tonight count.</p><p>© 2026 / Chumani Tikili</p></div></footer></div>}
